W Min
========================================================

```{r echo=F}
library(TTR)
source('DMin_fnc.R')

```

```{r echo = F}
Dax_tap <- read.csv("Dax_tap.csv")
dx_res <- calc_dm_today(Dax_tap) 

#b. ------------ CAC
CAC_tap <- read.csv("CAC_tap.csv")
cac_res <- calc_dm_today(CAC_tap)

# c. ------------ FTSE 
F100_tap <- read.csv("F100_tap.csv")
f100_res <- calc_dm_today(F100_tap)

# d. ------------ Dow 
Dow_tap <- read.csv("Dow_tap.csv")
dow_res <- calc_dm_today(Dow_tap)

# e. ------------ N225 
N225_tap <- read.csv("N225_tap.csv")
n225_res <- calc_dm_today(N225_tap)

# f. ------------ Oz 
Oz_tap <- read.csv("Oz_tap.csv")
oz_res <- calc_dm_today(Oz_tap)

paste(c('Dax',as.character.Date(Dax_tap$Date[nrow(Dax_tap)]),dx_res))
paste(c('CAC',as.character.Date(CAC_tap$Date[nrow(CAC_tap)]),cac_res))
paste(c('FTSE',as.character.Date(F100_tap$Date[nrow(F100_tap)]),f100_res))
paste(c('Dow',as.character.Date(Dow_tap$Date[nrow(Dow_tap)]),dow_res))
paste(c('N225',as.character.Date(N225_tap$Date[nrow(N225_tap)]),n225_res))
paste(c('Oz',as.character.Date(Oz_tap$Date[nrow(Oz_tap)]),oz_res))
```





```{r echo=F}
Dax_tap <- read.csv("Dax_tap.csv")
CAC_tap <- read.csv("CAC_tap.csv")
F100_tap <- read.csv("F100_tap.csv")
Dow_tap <- read.csv("Dow_tap.csv")
N225_tap <- read.csv("N225_tap.csv")
Oz_tap <- read.csv("Oz_tap.csv")
```


Dax
------------------------------
```{r echo=F}
dx_rr <- test(Dax_tap,2000)
dx_rr$pl2 <- ifelse(dx_rr$a4>0,dx_rr$pl,-dx_rr$pl)
dx_rr$smpl2 <- (SMA(dx_rr["pl2"], 10)) * 10
dx_rr$wl <- ifelse(dx_rr$pl2>0,1,0)
dx_rr$sm10 <- (SMA(dx_rr["wl"], 10)) * 10
tail(dx_rr[-c(6,7,8,10)],n=15)
```

CAC
------------------------------
```{r echo=F}
cc_rr <- test(CAC_tap,2000)
cc_rr$pl2 <- ifelse(cc_rr$a4>0,cc_rr$pl,-cc_rr$pl)
cc_rr$smpl2 <- (SMA(cc_rr["pl2"], 10)) * 10
cc_rr$wl <- ifelse(cc_rr$pl2>0,1,0)
cc_rr$sm10 <- (SMA(cc_rr["wl"], 10)) * 10
tail(cc_rr[-c(6,7,8,10)],n=15)
```

FTSE
------------------------------
```{r echo=F}
ft_rr <- test(F100_tap,2000)
ft_rr$pl2 <- ifelse(ft_rr$a4>0,ft_rr$pl,-ft_rr$pl)
ft_rr$smpl2 <- (SMA(ft_rr["pl2"], 10)) * 10
ft_rr$wl <- ifelse(ft_rr$pl2>0,1,0)
ft_rr$sm10 <- (SMA(ft_rr["wl"], 10)) * 10
tail(ft_rr[-c(6,7,8,10)],n=15)
```

Dow
------------------------------
```{r echo=F}
dw_rr <- test2(Dow_tap,2000)
dw_rr$pl2 <- ifelse(dw_rr$a4>0,dw_rr$pl,-dw_rr$pl)
dw_rr$smpl2 <- (SMA(dw_rr["pl2"], 10)) * 10
dw_rr$wl <- ifelse(dw_rr$pl2>0,1,0)
dw_rr$sm10 <- (SMA(dw_rr["wl"], 10)) * 10
tail(dw_rr[-c(6,7,8,10)],n=15)
```

Nik
------------------------------
```{r echo=F}
ni_rr <- test(N225_tap,2000)
ni_rr$pl2 <- ifelse(ni_rr$a4>0,ni_rr$pl,-ni_rr$pl)
ni_rr$smpl2 <- (SMA(ni_rr["pl2"], 10)) * 10
ni_rr$wl <- ifelse(ni_rr$pl2>0,1,0)
ni_rr$sm10 <- (SMA(ni_rr["wl"], 10)) * 10
tail(ni_rr[-c(6,7,8,10)],n=15)
```

OZ
------------------------------
```{r echo=F}
oz_rr <- test(Oz_tap,2000)
oz_rr$pl2 <- ifelse(oz_rr$a4>0,oz_rr$pl,-oz_rr$pl)
oz_rr$smpl2 <- (SMA(oz_rr["pl2"], 10)) * 10
oz_rr$wl <- ifelse(oz_rr$pl2>0,1,0)
oz_rr$sm10 <- (SMA(oz_rr["wl"], 10)) * 10
tail(oz_rr[-c(6,7,8,10)],n=15)
```
